spring.application.name=api-gateway
server.port=8080

spring.cloud.gateway.routes[0].id=booking-service
spring.cloud.gateway.routes[0].uri=http://booking-service:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/bookings/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1

# Route 2 : order-service
spring.cloud.gateway.routes[1].id=recommendation-service
spring.cloud.gateway.routes[1].uri=http://recommendation-service:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/recommendations/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1

management.endpoints.web.exposure.include=gateway
