spring.application.name=recommendation-service

server.port=8082


spring.data.mongodb.host=mongodb
spring.data.mongodb.port=27017
spring.data.mongodb.database=recommendationdb


spring.cloud.gcp.project-id=virtual-tape-504721-a5

spring.cloud.gcp.credentials.location=file:/app/gcp-key.json
