name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          - booking-service
          - recommendation-service
          - api-gateway
    
    defaults:
      run:
        working-directory: ${{ matrix.service }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven
      
      - name: Build
        run: mvn clean package -DskipTests

